spring:
  application:
    name: chatroom

springdoc:
  api-docs:
    path: /v3/api-docs

info:
  application:
    name: Chat Room

server:
  port: 8080

application:
  weather:
    url: http://localhost:8081/weather